Repository vnma0/hestia, pull requests merged in 2019-03, with the labels that each got.

#53 Write a proper README
  README.md
  doc/README.vi-VN.md
Labels: enhancement, help wanted

#62 Changing thumbnails for drawer items
  src/app/home/homepageLauncher.js
  src/app/problemList/problemLauncher.js
  src/app/scoreboard/scoreboardLauncher.js
  src/app/submissions/submissionLauncher.js
Labels: enhancement

#61 Adding error catching for logout call
  src/app/globalStatusBar/userSetting/stub/logout.js
Labels: bug, enhancement, priority

#60 [Async](stub/login.js) : Fetch userId right after logging in
  src/app/globalStatusBar/login/stub/credential.js
  src/app/globalStatusBar/login/stub/login.js
Labels: bug, priority

#58 Changing time format
  package.json
  src/app/globalStatusBar/clock/clock.js
  src/app/globalStatusBar/globalStatusBar.js
  src/app/submissions/submission.js
  src/external/timeAgo.js
  src/index.js
Labels: enhancement

#66 Clock : now shows no duplicate text upon contest ended
  src/app/globalStatusBar/clock/clock.js
  src/app/globalStatusBar/globalStatusBar.js
Labels: bug, enhancement

#73 Clock : let it calculate itself the time delta
  src/app/globalStatusBar/clock/clock.js
  src/app/globalStatusBar/globalStatusBar.js
  src/index.js
Labels: enhancement

#69 Hestia : Un-global & partial updates
  src/app/globalStatusBar/clock/clock.js
  src/app/globalStatusBar/globalStatusBar.js
  src/app/globalStatusBar/login/loginDialog.js
  src/app/globalStatusBar/login/stub/credential.js
  src/app/globalStatusBar/login/stub/login.js
  src/app/globalStatusBar/staticStub/public.js
  src/app/globalStatusBar/userSetting/passwordChange/passwordChangeDialog.js
  src/app/globalStatusBar/userSetting/stub/logout.js
  src/app/globalStatusBar/userSetting/stub/passwordChange.js
  src/app/globalStatusBar/userSetting/userSettingDialog.js
  src/app/notifier/notify.js
  src/app/problemList/codeEditor/codeBox.js
  src/app/problemList/codeEditor/codeEditor.js
  src/app/problemList/codeEditor/stub/submit.js
  src/app/problemList/codeEditor/submitButton.js
  src/app/problemList/problemList.js
  src/app/problemList/problemTab/problemTab.js
  src/app/problemList/problemTabEditor.js
  src/app/problemList/problemWrapper.js
  src/app/scoreboard/scoreboard.js
  src/app/scoreboard/scoreboardWrapper.js
  src/app/scoreboard/stub/score.js
  src/app/sidenav/sidenav.js
  src/app/submissions/stub/submission.js
  src/app/submissions/submissionDetail/detailedSubmission.js
  src/app/submissions/submissionTable.js
  src/external/timeAgo.js
  src/index.js
Labels: enhancement, priority

#83 Add clock tooltip
  src/app/globalStatusBar/clock/clock.css
  src/app/globalStatusBar/clock/clock.js
Labels: enhancement

#94 Hestia : no longer forces a full reload upon changing route
  src/app/sidenav/sidenav.js
  src/index.js
Labels: enhancement

#95 Keep up with verdict changes
  src/app/submissions/signature/verdictSignature.js
  src/app/submissions/stub/submission.js
Labels: enhancement

#96 Rewriting submission details panel
  package.json
  prettier.config.js
  src/app/submissions/stub/download.js
  src/app/submissions/submission.js
  src/app/submissions/submission/downloadCell.js
  src/app/submissions/submissionDetail/codePanel/codeDialog.js
  src/app/submissions/submissionDetail/codePanel/codePanel.js
  src/app/submissions/submissionDetail/detailedSubmission.js
  src/app/submissions/submissionDetail/submissionDetail.js
  src/app/submissions/submissionDetail/testBasedVerdictTable.js
  src/app/submissions/submissionTable.js
Labels: enhancement

#93 Add programmatical support for downloading source code back
  package.json
  prettier.config.js
  src/app/submissions/stub/download.js
  src/app/submissions/submission.js
  src/app/submissions/submissionDetail/codePanel/codeDialog.js
  src/app/submissions/submissionDetail/codePanel/codePanel.js
  src/app/submissions/submissionDetail/detailedSubmission.js
  src/app/submissions/submissionDetail/submissionDetail.js
  src/app/submissions/submissionDetail/testBasedVerdictTable.js
  src/app/submissions/submissionTable.js
Labels: enhancement

#99 Improve extParser.js
  src/app/problemList/codeEditor/extParser.js
Labels: enhancement

#92 CodeEditor : move to Ace, deprecating CodeMirror
  package.json
  src/app/problemList/codeEditor/codeEditor.js
  src/app/problemList/codeEditor/extParser.js
  src/app/problemList/codeEditor/langSelection.js
Labels: enhancement

#100 Submissions page now tells user to update
  src/app/submissions/stub/submission.js
  src/app/submissions/submissionWrapper.js
Labels: enhancement

#108 Display languages instead of extensions
  src/app/problemList/codeEditor/codeBox.js
  src/app/problemList/codeEditor/langSelection.js
  src/app/problemList/problemTabEditor.js
  src/app/submissions/signature/languageSignature.js
  src/app/submissions/stub/submission.js
  src/strings/lang.json
Labels: enhancement

#109 Bring back the ability to load a file into the editor
  src/app/problemList/codeEditor/codeBox.js
  src/app/problemList/codeEditor/confirmButton.js
  src/app/problemList/codeEditor/fileDisplay.js
  src/app/problemList/codeEditor/uploadButton.js
Labels: enhancement

#102 New Problems
  public/index.html
  src/app/problemList/codeEditor/codeBox.js
  src/app/problemList/codeEditor/codeEditor.js
  src/app/problemList/problemTab/problemTab.js
  src/app/problemList/problemTabEditor.js
  src/index.js
Labels: enhancement

#90 Add some color to Submissions page
  src/app/submissions/submission.css
  src/app/submissions/submission.js
Labels: enhancement

#103 Change page title when route changes
  src/app/home/homepage.js
  src/app/problemList/problemWrapper.js
  src/app/scoreboard/scoreboardWrapper.js
  src/app/submissions/submissionWrapper.js
  src/index.js
Labels: enhancement
